language: ruby
rvm:
  - 2.5

script:
  - bundle exec jekyll build

branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

sudo: false  # route your build to the container-based infrastructure for a faster build

cache: bundler  # caching bundler gem packages will speed up build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: false
  local-dir: _site
  target-branch: master
  on:
    branch: gh-pages

notifications:
  slack:
    rooms:
      - secure: "bi8L+2CCWF+DkvXzCqUNkds+ThoYtIGcS/bNBJC2+BPrI9+lP0dNAu+PGDoQuyG1Am1f8M3N9e21SnttJl6RtqOeKuj/WucsheGMpi7CkHp6nRzn5q1YSzNTlKuwcq7SYJ+GmOgAqzHQuGzZ2yCHMPXQwTdf4fBnpoK0DN+u6uhV7+Oo2vytXsSTfY4JGObs7y/2bqJSijF9TddsyqrLBrSPM1kqYEv7ltFiClmymGsd5RuaU5lwf2Lxi0Hfp/j0vGKxwOjCRlMH+lFLSiNB6ULbknguiKDx89Ko8WaDXMhXbJQobqeGx/3i+HFYqd/84ZTasrvAXgLbodefSmRcNYqIU/WRIL7LuvmGvhGr66yvXw9jAy3QyANjMW/8/yHcQ5MM+axvkZnopqG1GBxZhxf4NQALi06jd5TxSmJydd4/4r15kW3pd0eDFNu+5WaRnltHO+brwknVuX1R7PKPTIbTheQmvm35T+ORiwMLW0rGrUFk0OP7d4yQmJouhnnLju51i+/aXYRkB8SZUEwlgD7mIdzvfC0aAZeLjXHwwTXD5iHnfnRGDXum3zuQRTQ2tNxoKz8yjQbWnzbzVc8EFHxXGibeAhzqk9jQ6xT1KyEECe7Ry4XEsVwGGJVvcCP1YcJWZfarq2DT54iWMFCmZQAoCPBdtLx138P0EsmPpM8="
    on_success: always
