#
# Jekyll configuration file

# Global configuration
source: src
destination: ./_site
exclude: [ 'Gemfile', 'Gemfile.lock', '.gitignore', 'vendor', 'docker-compose.yml', 'LICENSE', '.travis.yml' ]
encoding: UTF-8

# Conversion
markdown: kramdown
highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins: [ 'jekyll-paginate-v2' ]

# Plugin - 'jekyll-paginate-v2'
pagination:
  enabled: true
  permalink: '/page/:num/'
  per_page: 5
  sort_field: 'date'
  sort_reverse: true

# Plugin - Discus
comments: false

# SEO settings
title: "Jterral's pages"
description: "A short description of your site's purpose"
keywords: "blog, web, coding, developer"
url: https://jterral.github.io/

# Custom
repo: https://github.com/jterral/jterral.github.io
# google_analytics: TODO
# disqus_shortname: TODO
# disqus_site_shortname: TODO

# Author settings
author:
  name: Jonathan Trl
  job: Software Engineer
  bio: "Currently working as .NET Core backend developer in Azure environment."
  thumb: /images/author.jpg
  url: https://jterral.github.io/
  github: https://github.com/jterral
  twitter: https://twitter.com/Jonathan_Trl
  linkedin: https://www.linkedin.com/in/jonathan-trl/

# Navbar
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
