#
# Azure Pipelines

trigger:
- gh-pages

pool:
  vmImage: 'ubuntu-latest'

variables:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  gh_user: jterral
  gh_repo: jterral.github.io
  gh_pass: $(GITHUB_TOKEN)

steps:
- task: UseRubyVersion@0
  displayName: '[Ruby] Use Ruby >= 2.5'
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: |
    sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
  displayName: '[Apt] apt-get install ruby-dev'

- script: |
    gem install bundler
  displayName: '[Gem] Install bundler'

- script: |
    gem install jekyll
  displayName: '[Gem] Install jekyll'

- script: |
    ls -al
    bundle install --retry=3 --jobs=4
  displayName: '[Jekyll] Bundle install'

# - task: Bash@3
#   displayName: 'jekyll build'
#   inputs:
#     targetType: 'inline'
#     script: |
#       jekyll build

# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
#   inputs:
#     SourceFolder: '_site'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: site
