#
# Azure Pipelines

trigger:
- gh-pages

pool:
  vmImage: 'ubuntu-latest'

variables:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  gh_user: jterral
  gh_repo: jterral.github.io
  gh_pass: $(GITHUB_TOKEN)
  gh_mail: jonathan.terral@outlook.com

steps:
- task: UseRubyVersion@0
  displayName: '[Ruby] Use Ruby >= 2.5'
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- script: |
    sudo apt-get install libxslt-dev libxml2-dev
  displayName: '[Apt] Install dev dependencies'

- script: |
    gem install bundler
  displayName: '[Gem] Install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: '[Jekyll] Bundle install'

- script: |
    bundle exec jekyll build
  displayName: '[Jekyll] Build Jekyll Static Site to _site'

- script: |
    ls -al
  displayName: '[Script] ls -al'

- task: CopyFiles@2
  displayName: '[Script] Copy files to: $(Build.StagingDirectory)'
  inputs:
    sourceFolder: '_site'
    targetFolder: $(Build.StagingDirectory)

- task: CopyFiles@2
  displayName: '[Script] Copy .git to: $(Build.StagingDirectory)'
  inputs:
    sourceFolder: '.git'
    targetFolder: $(Build.StagingDirectory)/.git

- script: |
    ls -al $(Build.StagingDirectory)
  displayName: '[Script] ls -al $(Build.StagingDirectory)'

- script: |
    git config user.email $(gh_mail)
    git config user.name $(gh_user)
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Configure User'

- script: |
    git add --all
    git commit -m "Azure Pipelines Bot: Updated site via $(Build.SourceVersion)"
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Creating commit'

- script: |
    git push origin master
  workingDirectory: $(Build.StagingDirectory)
  displayName: '[Git] Push changes to master'
