#
# Azure Pipelines

trigger:
- gh-pages

pool:
  vmImage: 'ubuntu-latest'

variables:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  gh_user: jterral
  gh_repo: jterral.github.io
  gh_pass: $(GITHUB_TOKEN)

steps:
- task: Bash@3
  displayName: 'apt-get install'
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get install ruby-all-dev

- task: UseRubyVersion@0
  displayName: 'Select Ruby version'
  inputs:
    versionSpec: '>= 2.5'
    addToPath: true

- task: Bash@3
  displayName: 'gem install'
  inputs:
    targetType: 'inline'
    script: |
      gem install jekyll bundler
      bundle install --retry=3 --jobs=4

- task: Bash@3
  displayName: 'jekyll build'
  inputs:
    targetType: 'inline'
    script: |
      jekyll build

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '_site'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: site
