#
# Jekyll run for testing purposes
version: '3'

services:
    jekyll:
        image: jekyll/jekyll:latest
        container_name: jtrl_pages
        command: jekyll serve --watch --incremental
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
