#
# docker-compose file to test Jekyll website.
version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll_dev
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - $PWD:/srv/jekyll
