name: jterral_github_io
version: 1.0.0+1
description: Jonathan Terral's home web
homepage: https://jterral.github.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.4.3
  font_awesome_flutter: ^8.7.0
  url_launcher: ^5.4.2
  universal_html: ^1.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
