name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: withastro/action@v5
        with:
          path: .
          node-version: 24

  versioning:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_calver.outputs.tag }}
      version: ${{ steps.get_calver.outputs.version }}
    steps:
      - id: get_calver
        uses: jterral/calendar-versioning-action@v1
        with:
          tag-push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

  deploy:
    needs: versioning
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
